#server:
#  port: 8081
    
# Oracle #
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: MICROJAVA220822
#    password: 123456
#    driver-class-name: oracle.jdbc.driver.OracleDriver